In [ ]:
#Arrays
#NUMPy (numerical python)

x=[1,2,3]
for i in x:
  print(i/2)

0.5
1.0
1.5


In [ ]:
import numpy as np
x=np.array([2,4,6,8,10])
print(x)

[ 2  4  6  8 10]


In [ ]:
x*2

array([ 4,  8, 12, 16, 20])

In [ ]:
#Random Functions:

import numpy as np
np.random.randint(0,10,4)

array([7, 7, 0, 3])

In [ ]:
array=np.random.randint(0,10,(3,3))
array

array([[7, 1, 6],
       [6, 9, 6],
       [7, 7, 3]])

In [ ]:
np.random.randint(0,10,(2,3))

array([[3, 0, 1],
       [7, 7, 6]])

In [ ]:
data = np.random.randint(0,10,(5,4))
data

array([[6, 8, 1, 9],
       [6, 6, 8, 0],
       [6, 8, 3, 9],
       [1, 6, 2, 1],
       [1, 5, 6, 6]])

In [ ]:
data[1: , :2]

array([[6, 6],
       [6, 8],
       [1, 6],
       [1, 5]])

In [ ]:
data[2:4,1: ]

array([[8, 3, 9],
       [6, 2, 1]])

In [ ]:
#Initiaize numpy arrays
import numpy as np
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
import numpy as np
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
import numpy as np
np.full((4,4),-6)

array([[-6, -6, -6, -6],
       [-6, -6, -6, -6],
       [-6, -6, -6, -6],
       [-6, -6, -6, -6]])

In [ ]:
#1D arrays
a= np.array([1,2,3])
print(a)
print(type(a))
a.ndim


[1 2 3]
<class 'numpy.ndarray'>


1

In [ ]:
#2D arrays

a= np.array([[1,2,3],[3,4,5],[6,7,8]])
print(a)
print(type(a))
a.ndim

[[1 2 3]
 [3 4 5]
 [6 7 8]]
<class 'numpy.ndarray'>


2

In [ ]:
#3D arrays

x=np.array([[[1,2,3],[4,5,6]],[[6,7,8],[7,8,9]]])
print(x)
print(type(x))
x.ndim

[[[1 2 3]
  [4 5 6]]

 [[6 7 8]
  [7 8 9]]]
<class 'numpy.ndarray'>


3

In [ ]:
#initilize 'x' and 'y' with an interval of z

np.arange(0,101,10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
np.linspace(5,10,4)

array([ 5.        ,  6.66666667,  8.33333333, 10.        ])

In [ ]:
np.arange(5,10,4)

array([5, 9])

In [ ]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [ ]:
np.linspace(9,90,10)

array([ 9., 18., 27., 36., 45., 54., 63., 72., 81., 90.])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
import numpy as np
data =np.array([[6, 8, 1, 9],
       [6, 6, 8, 0],
       [6, 8, 3, 9],
       [1, 6, 2, 1],
       [1, 5, 6, 6]])
print(data)

[[6 8 1 9]
 [6 6 8 0]
 [6 8 3 9]
 [1 6 2 1]
 [1 5 6 6]]


In [ ]:
data.min()

np.int64(0)

In [ ]:
data.max()

np.int64(9)

In [ ]:
data.avg()

AttributeError: 'numpy.ndarray' object has no attribute 'avg'

In [ ]:
b=np.array([[4,5,6],[6,8,10]])
print(b.shape)

(2, 3)


In [ ]:
a=np.array([[2,4,6,4],[5,6,7,8],[8,10,12,4]])
print("Original Array:\n",a)
a.shape=(6,2)
print("Changed Array:\n",a)

a.shape=(4,3)
print("Changed Array:\n",a)


Original Array:
 [[ 2  4  6  4]
 [ 5  6  7  8]
 [ 8 10 12  4]]
Changed Array:
 [[ 2  4]
 [ 6  4]
 [ 5  6]
 [ 7  8]
 [ 8 10]
 [12  4]]
Changed Array:
 [[ 2  4  6]
 [ 4  5  6]
 [ 7  8  8]
 [10 12  4]]


In [ ]:
b=np.array([[1,2,3],[4,5,6],[5,8,8],[5,6,4]])
print(b)
b.shape=(1,12)
print(b)
b.shape=(2,6)
print(b)


[[1 2 3]
 [4 5 6]
 [5 8 8]
 [5 6 4]]
[[1 2 3 4 5 6 5 8 8 5 6 4]]
[[1 2 3 4 5 6]
 [5 8 8 5 6 4]]


In [ ]:
z=np.arange(24)
#print(z)
z.shape=(2,6,2)
print(z)
print(z.ndim)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]
  [18 19]
  [20 21]
  [22 23]]]
3


In [ ]:
z=np.arange(30)
#print(z)
z.shape=(1,10,3)
print(z)
print(z.ndim)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
3


In [ ]:
import numpy as np

In [ ]:
a=np.array([[1,2,3],[4,5,6],[5,8,12]])
print(a.size)
print(a.shape)
print(a.ndim)
print(a.dtype)

9
(3, 3)
2
int64


In [ ]:
import numpy as np

x=np.random.randint(0,20,(6,5))
print(x)

[[11  8  3  5 17]
 [18 18  0  3 19]
 [19 13 11  5  1]
 [12  2  2  2 10]
 [18 14  7  2 16]
 [ 2 15  8  8 17]]


In [ ]:
x.shape()     #30=1*30,2*15,3*10,6*5,15*2


In [ ]:
x.ravel()


array([11,  8,  3,  5, 17, 18, 18,  0,  3, 19, 19, 13, 11,  5,  1, 12,  2,
        2,  2, 10, 18, 14,  7,  2, 16,  2, 15,  8,  8, 17])

In [ ]:
y=x.ravel()

In [ ]:
y.reshape(10,3)
print(x)

[[11  8  3  5 17]
 [18 18  0  3 19]
 [19 13 11  5  1]
 [12  2  2  2 10]
 [18 14  7  2 16]
 [ 2 15  8  8 17]]


In [ ]:
x1=np.array([[2,3],[4,3]])
print(x1)

[[2 3]
 [4 3]]


In [ ]:
x2=np.array([[4,5],[6,7]])
print(x2)

[[4 5]
 [6 7]]


In [ ]:
np.vstack([x1,x2])

array([[2, 3],
       [4, 3],
       [4, 5],
       [6, 7]])

In [ ]:
np.hstack([x1,x2])

array([[2, 3, 4, 5],
       [4, 3, 6, 7]])

In [ ]:
np.concatenate([x1,x2],axis=0)

array([[2, 3],
       [4, 3],
       [4, 5],
       [6, 7]])

In [ ]:
np.concatenate([x1,x2],axis=1)

array([[2, 3, 4, 5],
       [4, 3, 6, 7]])

In [ ]:
import numpy as np
np.sum([10,30,60,54,68,258])

np.int64(480)

In [ ]:
a=[10,20]
b=[20,5]

np.sum([a,b])

np.int64(55)

In [ ]:
import numpy as np

#creating two2D arrays
array1 = np.array([[1,2,3],
                   [4,5,6]])

array2 = np.array([[7,8,9],
                   [10,11,12]])

array3 = np.array([[8,6,9],
                    [10,9,13]])

sum_array = array1+array2+array3
print("Addition:\n", sum_array)
sum_array.ndim


Addition:
 [[16 16 21]
 [24 25 31]]


2

In [ ]:
import numpy as np

np.subtract(10,20)

np.int64(-10)

In [ ]:
a=np.array([0,1])
b=np.array([0,5])

np.subtract(a,b)

array([ 0, -4])

In [ ]:
a=np.array([0,1,6])
b=np.array([0,5,3])

np.subtract(a,b)

array([ 0, -4,  3])

In [ ]:
a=np.array([0,1,6])
b=np.array([0,5,3])
c=np.array([0,1,2])

sub=a-b-c
print(sub)

[ 0 -5  1]


In [ ]:
import numpy as np

a= np.array([[1,2],[6,8],[6,5]])
b=np.array([5,4])

result=a+b
print("result of a+b")

result of a+b


In [2]:
import numpy as np

array1 = np.array([[1,2,3],
                  [4,5,6]])

array2 = np.array([[7,8,9],
                   [10,11,12]])

product_array = array1*array2
print("Multiplication:\n",product_array)

Multiplication:
 [[ 7 16 27]
 [40 55 72]]


In [3]:
array1 = np.array([[1,2,3],
                   [4,5,3],
                   [4,6,1]])
array2 = np.array([[7,8,4],
                   [4,1,2],
                   [2,3,2]])
product_array = array1*array2
print("Multiplication:\n",product_array)

Multiplication:
 [[ 7 16 12]
 [16  5  6]
 [ 8 18  2]]


In [ ]:
#Matrix Multiplication
m*n, n*k

In [6]:
x1=np.random.randint(0,10,(2,2))
x2=np.random.randint(0,10,(2,2))


In [7]:
x1

array([[5, 1],
       [5, 7]])

In [8]:
x2

array([[4, 0],
       [0, 5]])

In [9]:
np.dot(x1,x2)

array([[20,  5],
       [20, 35]])