Create a function that takes dimensions as tuples e.g. (3, 3) and a numeric
value and returns a NumPy array of the given dimension filled with the
given value e.g.: solve((3, 3), 5) will return
 [

 [5, 5, 5],
 [5, 5, 5],
 [5, 5, 5]
 ]

In [ ]:
import numpy as np

def solve(dimensions, value):
     return np.full(dimensions,value)

result = solve((3,3),5)
print(result)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


Create a method that takes n NumPy arrays of the same dimensions,
sums them and returns the answer.

In [ ]:
import numpy as np

def sum_arrays(*arrays):
    return np.sum(arrays,axis=0)

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr3 = np.array([[9,10],[11,12]])

result = sum_arrays(arr1,arr2,arr3)
print("Summed Array:\n",result)

Summed Array:
 [[15 18]
 [21 24]]


Given a 2 D Array of N X M Dimension, write a function that accepts this
array as well as two numbers N and M. The method should return the
top-left N X M sub matrix, e.g:
 [
 ]
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],

In [ ]:
import numpy as np
def get_submatrix(array,N,M):
  return array[:N,:M]

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

result = get_submatrix(matrix,2,2)
print("Top-left sub-matrix:\n",result)

Top-left sub-matrix:
 [[1 2]
 [4 5]]


Given a 2 D Array of N X M Dimension, write a function that accepts this
array as well as two numbers N and M. The method should return the
bottom-right N X M sub matrix, e.g:
 [

 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 ]

In [3]:
import numpy as np
def bottom_right_sub_matrix(matrix, n, m):
  return [row[-m:] for row in matrix[-n:]]

matrix = [[1,2,3],
          [4,5,6],
          [7,8,9]]

sub_matrix = bottom_right_sub_matrix(matrix, 2, 2)
print(sub_matrix)

[[5, 6], [8, 9]]


Given a 1 D NumPy Array. Write a function that accepts this array as
parameters. The method should return a dictionary with 'mean' and
'std_dev' as key and array's mean and array's standard deviation as
values:
 [1, 1, 1]

In [4]:
import numpy as np
def array_stats(arr):
  return{"mean":np.mean(arr),"std_dev":np.std(arr)}


arr=np.array([1,1,1])
stats = array_stats(arr)
print(stats)

{'mean': np.float64(1.0), 'std_dev': np.float64(0.0)}
