<a href="https://colab.research.google.com/github/Revathi9n/github-pages/blob/main/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#What is Python
#Python is a high level interpreted and object orinted programming language.
#It was created by Guido van rossum and first released in 1991.


In [ ]:
#Key features of python
#1.Easy to read and write
#2.Interpreted language
#3.object oriented
#4.versatile and extensible
#5.large standard library
#6.cross platform

#Application of python
#1.web development
#2.Data science and machine learing
#3.Automation and scripting
#4.Game development
#5.Arificial Intelligence

In [ ]:
A=10


In [ ]:
A

10

In [ ]:
print("Hello world!")

Hello world!


In [ ]:
A="Python Programming"

In [ ]:
A.lower()

'python programming'

In [ ]:
A.upper()

'PYTHON PROGRAMMING'

In [ ]:
A.title()

'Python Programming'

In [ ]:
A.isalpha()

False

In [ ]:
A.isalnum()

False

In [ ]:
S="Data Science"

In [ ]:
S[5:]

'Science'

In [ ]:
S[0:4]

'Data'

In [ ]:
S[ : ]

'Data Science'

In [ ]:
S[0:10]

'Data Scien'

Arithmetic Operations

In [ ]:
x=10
y=20
addition = x+y
print(f"addition:{x}+{y} ={addition}")


addition:10+20 =30


In [ ]:
x=8
y=9
subtraction=x-y
print(f"subtraction:{x}-{y}={subtraction}")

subtraction:8-9=-1


In [ ]:
x=16
y=4
multiplication=x*y
print(f"multiplication:{x}*{y}={multiplication}")

multiplication:16*4=64


Conditional Statements


In [ ]:
Tomato=15
if Tomato<=20:
  print("bring 1kg of Tomato")

bring 1kg of Tomato


In [ ]:
tomato = int(input("tomatotes cost per kg:\n"))
if tomato<40:
  print("bring 5 kg of tomatotes")
elif tomato<=50:
  print("print 2kg of tomatotes")
else:
  print("bring 1kg of tomatotes")


tomatotes cost per kg:
90
bring 1kg of tomatotes


In [25]:
age=int(input())
has_permission=True
if age>=18:
  if has_permission:
    print("Allowed")
  else:
    print("Not Allowed")
else:
  if age>=13:
    print("Allowed with Guardian")
  else:
    print("You are not allowed")

2
You are not allowed


In [26]:
Name =input()

if Name =="Rahul":
  print("Welcome Rahul")
elif Name == "Sanju":
  print("Welcome Sanju")
else:
  print("What's your name ?")

rahul
What's your name ?


In [27]:
x = int(input("Enter a value for x:\n"))     #15
if x > 10:
    print("x is greater than 10")
    if x > 20:
        print("x is also greater than 20")
    else:
        print("x is not greater than 20")
else:
    print("x is 10 or less")

Enter a value for x:
2
x is 10 or less


In [28]:
for i in [1,2,3,4,5]:
  print(i*10,end =',')

10,20,30,40,50,

In [29]:
numbers = [1,'a',2,'b',3,4,5]
for num in numbers:
    print(num,end='')

1a2b345

In [30]:
for i in [1,2,3,4,5]:
    print(i+10,end=',')

11,12,13,14,15,

In [31]:
for i in [1,2,3,4,5]:
    print(i*"*")

*
**
***
****
*****


In [33]:
n=5
for i in range(n):
  print(""*(n-i-1)+"*"*(i+1))
for i in range(n-2,-1,-1):
    print(""*(n-i-1)+"*"*(i+1))

*
**
***
****
*****
****
***
**
*


In [34]:
n=5
#upper part of the diamond
for i in range(1,n+1):   #1,2,3,4,5
  print(("*"*(2*i-1)).center(2*n-1))
#lower part of the diamond
for j in range(n-1,0,-1):    #4,3,2,1
  print(("*"*(2*j-1)).center(2*n-1))

    *    
   ***   
  *****  
 ******* 
*********
 ******* 
  *****  
   ***   
    *    


In [35]:
import numpy as np
x=np.array([2,4,6,8,10])
print(x)

[ 2  4  6  8 10]


In [38]:
import numpy as np
np.random.randint(0,10,6)


array([2, 5, 1, 8, 7, 8])

In [39]:
array=np.random.randint(0,10,(3,4))
array

array([[3, 5, 3, 7],
       [7, 5, 3, 2],
       [4, 6, 7, 5]])

In [40]:

import numpy as np

def sum_arrays(*arrays):
    return np.sum(arrays,axis=0)

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr3 = np.array([[9,10],[11,12]])

result = sum_arrays(arr1,arr2,arr3)
print("Summed Array:\n",result)

Summed Array:
 [[15 18]
 [21 24]]
